---
title: Creative Coding for Creative Teachers
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
tagline:
url: http://bsk.education/CreativeCodingCreativeTeachers
# paginate: 0
baseurl: "/CreativeCodingCreativeTeachers"
sass:
  sass_dir: _sass
  style: :compressed
author:
  name: Ben Samuels-Kalow
  url: http://bsk.education
  email: bensamuelskalow@gmail.com
version: 2.0.0
github:
  repo: https://github.com/bensk
plugins:
- jekyll-archives
# - jekyll-paginate
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"
future: true
include: ['_pages']
pages: ./_pages
